language: ruby
rvm:
  - 2.0.0
before_script:
  - psql -c 'CREATE ROLE rtp NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN;' -U postgres
  - psql -c 'CREATE DATABASE rtp_test WITH OWNER rtp;' -U postgres
script: "RAILS_ENV=test bundle exec rake db:schema:load; bundle exec rspec spec"
deploy:
  provider: heroku
  api_key: 994add75-14df-4e79-b039-1b5c8dc1648a
