# Postgres SQL
development:
  adapter: postgresql
  database: rtp
  pool: 5
  username: rtp
  password:

test:
  adapter: postgresql
  database: rtp_test
  pool: 5
  username: rtp
  password:

production:
  adapter: postgresql
  database: rtp
  pool: 5
  username: rtp
  password: rtp
